classes/image_types_ostree.bbclass
conf/distro/sota.conf.inc
recipes-sota/ostree/ostree_git.bb
recipes-sota/rvi-sota-client/rvi-sota-client_git.bb
recipes-support/libgsystem/libgsystem_git.bb

Systemd is not really needed for OSTree, and it would be nice to give users a choice.

Make systemd optional

---

conf/include/local/sota_qemux86-64.inc

See PRO-2693 for details
Does this need a _sota suffix too?

Force version of Kernel to 4.4 to fix qemu crash

---

scripts/qa

This is a basic script to run bitbake over multiple build* directories

Script to build over multiple directories

---

classes/image_types_ota.bbclass
conf/distro/sota.conf.inc
recipes-core/images/initramfs-ostree-image.bb

Sane defaults to make arbitrary board build successfully

Merge changes required by AGL

---

recipes-sota/rvi-sota-client/rvi-sota-client_git.bb
recipes-support/python-petname/python-petname.bb

This adds the recipe in preparation for https://github.com/advancedtelematic/rvi_sota_client/pull/234 getting merged.

PRO-3157 Add recipe for friendly name generator

---

recipes-sota/rvi-sota-client/rvi-sota-client_git.bb

Just a bump to the latest client to fix some bugs.

Bump client version to fix PRO-3208 + PRO-3196

---

recipes-sota/ostree/ostree_git.bb

libsoup has issues with mutual TLS authentication

Build OSTree with curl support

---

classes/image_types_ota.bbclass

Preserve /var/local

---

classes/image_types_ostree.bbclass
recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/aktualizr/files/aktualizr-autoprovision.service

Perform sync() after provisioning
Store sota.toml in updatable /usr directory

Aktualizr updates, including sync()

---

classes/sdcard_image-rpi-ota.bbclass
classes/sota_raspberrypi.bbclass

@dl9pf Couldn't commit to your pull request. Fixed the bug @leon-anavi found.

Compress rpi-sdimg-ota

---

recipes-sota/aktualizr/aktualizr_git.bb

Fix issues with the random generated device ID.

aktualizr: Update to 207898e

---

recipes-sota/sota-tools/sota-tools_git.bb

This fixes a build error on Ubuntu.

Bump version of sota-tools

---

recipes-sota/rvi-sota-client/rvi-sota-client.inc
recipes-sota/rvi-sota-client/rvi-sota-client_git.bb
recipes-sota/rvi-sota-client/sota-launcher_git.bb

- bump sota-client version to b9170df

fix dependency of sota-launcher to correct rvi-sota-client

---

scripts/run-qemu-ota

Didn't realize the run-qemu script was in meta-updater too.

PRO-3923 Add persistence option to run-qemu script

---

classes/image_types_ostree.bbclass
recipes-extended/cronie/cronie_%.bbappend
recipes-extended/cronie/files/Disable-hard-link-check-by-default.patch

Fix cronie and OSTree conflicts

---

classes/sota.bbclass
recipes-sota/aktualizr/aktualizr-auto-prov.bb
recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/aktualizr/files/LICENSE

Split Aktualizr binary and systemd service and configurations in two separate Yocto/OE recipes:
* aktualizr that provides the binary
* aktualizr-pro that provides the systemd services and configurations for manual or autoprovision of Aktualizr.
Best regards,
Leon

Split Aktualizr binary and systemd service/configuration

---

classes/image_types_ostree.bbclass
classes/sota.bbclass
classes/sota_bleeding.inc
recipes-sota/aktualizr/aktualizr-auto-prov.bb
recipes-sota/aktualizr/aktualizr-implicit-prov.bb
recipes-sota/aktualizr/aktualizr-native_git.bb
recipes-sota/aktualizr/aktualizr_common.inc
recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/aktualizr/files/sota_implicit_prov.toml

To test this, you will need to use https://github.com/advancedtelematic/aktualizr/pull/362.
You will also need to add something like this to your local.conf:
```
DISTRO_FEATURES_append = " implicit-prov "
BRANCH_pn-aktualizr = "feat/PRO-3799/implicit-writer"
BRANCH_pn-aktualizr-native = "feat/PRO-3799/implicit-writer"
require classes/sota_bleeding.inc
```
You will need to use aktualizr_cert_provider to get the key and certificate on the device (unless you are using p11 or want to do it manually).

Feat/pro 3799/implicit writer

---

recipes-sota/garage-sign/garage-sign.bb

Update md5 and sha256 checksums of the archive.

garage-sign: Update checksums

---

recipes-devtools/pseudo/files/fix-posix-acl.patch
recipes-devtools/pseudo/pseudo_1.8.1.bbappend

Thanks to @guyshapiro for reporting.

Backport bugfix for POSIX ACL from pyro

---

classes/image_types_ostree.bbclass
recipes-sota/aktualizr/aktualizr_git.bb
recipes-support/ca-certificates/ca-certificates_%.bbappend

Explicitly include ca-certificates as a dependency for garage-push

---

README.adoc
lib/oeqa/selftest/garage_push.py

Add notes about oe-selftest to the README and add a test case for hsm hsm-test.
Best regards,
Leon

oe-selftest

---

classes/image_types_ostree.bbclass
classes/sota.bbclass
recipes-sota/garage-sign/garage-sign.bb

Add managing targets.json by garage-sign

---

lib/oeqa/selftest/updater.py

Rebased version of https://github.com/advancedtelematic/meta-updater/pull/175.

Test/pro 4229/oe selftest hsm

---

classes/image_types_ostree.bbclass
recipes-sota/aktualizr/aktualizr_git.bb

Also pass this URL to garage-sign.
Waiting for targets keys format being fixed to test that.

Rename repo.url -> tufrepo.url

---

recipes-sota/aktualizr/aktualizr_git.bb

Bump aktualizr version for good

---

classes/sota_raspberrypi.bbclass

The image is incompatible with meta-updater and we have our own

Remove sdimg-rpi from IMAGE_FSTYPES

---

scripts/qemucommand.py

Also fix a pylint warning about indentation

Add a hint when machine autodetection fails

---

recipes-sota/aktualizr/aktualizr-auto-prov.bb
recipes-sota/aktualizr/aktualizr-hsm-test-prov.bb
recipes-sota/aktualizr/aktualizr-implicit-prov.bb
recipes-sota/aktualizr/aktualizr_git.bb

OE standard is apparently four spaces.

Consistent indents.

---

README.adoc
classes/image_types_ostree.bbclass

Also add a missing mkdir so that SOTA_SECONDARY_ECUS actually works. We can improve this in the future but for now it works and I'm using it.

Update documentation, specifically about variables to support secondaries

---

recipes-sota/ostree/files/0001-Allow-building-without-libsoup.patch
recipes-sota/ostree/ostree_git.bb
recipes-support/glib-networking/glib-networking_%.bbappend
recipes-support/libsoup/libsoup-2.4_%.bbappend

It makes supporting different platforms (latest Archlinux in my case) somewhat easier.

Delete dependency on libsoup

---

recipes-sota/aktualizr/aktualizr-auto-prov.bb
recipes-sota/aktualizr/aktualizr-hsm-test-prov.bb
recipes-sota/aktualizr/aktualizr-implicit-prov.bb
recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/aktualizr/files/aktualizr-serialcan.service
recipes-support/slcand-start/files/slcand@.service
recipes-support/slcand-start/slcand-start.bb

Current implementation is quite hacky, created a ticket in Jira to make it (and similar tasks) better.
https://advancedtelematic.atlassian.net/browse/PRO-4572

Add support of ISO/TP legacy secondaries and serial CAN

---

README.adoc
lib/oeqa/selftest/cases/updater.py

Also add a helpful hint for the oe-selftest grub problem.

Add a brief doc section for common build problems.

---

README.adoc
recipes-sota/aktualizr/aktualizr-hsm-prov.bb
recipes-sota/aktualizr/aktualizr_git.bb

Bring rocko up to speed with latest aktualizr, HSM, and doc changes from pyro.

Feat/prj 330/hsm not test rocko

---

recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/asn1c/asn1c.bb
recipes-sota/asn1c/files/skeletons_dir_fix.patch

As you'll see, this required a little hack.
Required for https://github.com/advancedtelematic/aktualizr/pull/509 (which is not ready yet)

Compile aktualizr with asn1c help from yocto

---

classes/image_types_ostree.bbclass
classes/image_types_ota.bbclass
classes/sota_minnowboard.bbclass

Some bits were still missing after the transition, merge them

Merge pyro into rocko

---

recipes-sota/aktualizr/aktualizr_git.bb

I have not tested this at all.

Latest aktualizr/garage-sign.

---

CONTRIBUTING.adoc
recipes-sota/aktualizr/aktualizr_git.bb

Sync latest rocko-specific changes into the master branch.

Merge latest changes from the rocko branch

---

README.adoc
lib/oeqa/selftest/updater.py
recipes-sota/aktualizr/aktualizr_git.bb

This greatly expands the HSM testing of oe-selftest and improves a bunch of other tests as well.

Test/pro 4481/hsm

---

recipes-sota/aktualizr/aktualizr_git.bb

@EpicNuts Should be fixed now.

Pull new aktualizr with fixed fd leak

---

lib/oeqa/selftest/updater.py

This PR is based on https://github.com/advancedtelematic/meta-updater/pull/260

oe-selftest for implicit provisioning

---

lib/oeqa/selftest/cases/updater.py
recipes-test/demo-network-config/files/25-dhcp-server.network
recipes-test/demo-network-config/files/26-dhcp-client.network
recipes-test/demo-network-config/primary-network-config.bb
recipes-test/demo-network-config/secondary-network-config.bb
recipes-test/images/primary-image.bb
recipes-test/images/secondary-image.bb
scripts/qemucommand.py
scripts/run-qemu-ota

Resolves: PRO-5060
Resolves: PRO-5077

run-qemu-ota support for secondaries

---

lib/oeqa/selftest/cases/updater.py
recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/aktualizr/files/aktualizr-secondary.socket

Also, timeout communication to the DUT after 60s.

UDP Socket activation for discovery service

---

recipes-sota/aktualizr/aktualizr_git.bb

Needed to work with the addition of aktualizr-check-discovery

Bump aktualizr

---

classes/image_types_ostree.bbclass
recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/aktualizr/environment.inc
recipes-sota/aktualizr/files/aktualizr.service
recipes-test/images/primary-image.bb
recipes-test/images/secondary-image.bb

Includes the suggestion for using /etc/sota/sota.env if it exists as recommended by the discussion here:
https://github.com/advancedtelematic/meta-updater/pull/275
Also bumps aktualizr/garage-sign. Garage-sign still seems quite flaky.

Assorted minor cleanup and formatting.

---

recipes-sota/aktualizr/aktualizr-auto-prov.bb
recipes-sota/aktualizr/aktualizr-ca-implicit-prov.bb
recipes-sota/aktualizr/aktualizr-hsm-prov.bb
recipes-sota/aktualizr/aktualizr-implicit-prov.bb
recipes-sota/aktualizr/aktualizr_git.bb

Missing directories in FILES_xx were causing bitbake QA errors on sumo

Review shipped directories in aktualizr recipes

---

classes/sota_minnowboard_uboot.inc

See https://github.com/advancedtelematic/meta-updater-minnowboard/pull/6

Remove support for u-boot on minnowboard

---

scripts/find_packages.py

There will not be recipes for those packages, so don't go looking for them. We don't need them, anyway.

find_packages.py: Ignore packages in ASSUME_PROVIDED.

---

lib/oeqa/selftest/cases/updater.py
recipes-sota/aktualizr/aktualizr-hsm-prov.bb
recipes-sota/aktualizr/aktualizr-implicit-prov.bb
recipes-sota/aktualizr/aktualizr_git.bb

Note that the HsmTests still sometimes fail

Compatibility with latest aktualizr

---

recipes-sota/aktualizr/aktualizr_git.bb

@EpicNuts this should fix the meta-updater build problem you encountered.

Bump aktualizr to latest and fix googletest complaint.

---

lib/oeqa/selftest/cases/updater.py
recipes-sota/aktualizr/aktualizr_git.bb

Backported manual aktualizr update test.

Bump aktualizr to latest (sumo, again).

---

recipes-sota/aktualizr/aktualizr_git.bb

aktualizr: bump to latest and accommodate hmi_stub.

---

recipes-sota/aktualizr/aktualizr_git.bb
recipes-support/softhsm-testtoken/files/createtoken.sh

(sumo) softhsm-testtoken: Update paths for token import.

---

recipes-sota/aktualizr/aktualizr_git.bb
recipes-support/softhsm-testtoken/files/createtoken.sh

softhsm-testtoken: Update paths for token import.

---

classes/image_types_ota.bbclass
lib/oeqa/selftest/cases/updater.py
recipes-sota/aktualizr/aktualizr_git.bb

Will need https://github.com/advancedtelematic/aktualizr/pull/945 to be merged and aktualizr bumped (bump should be pushed later in this PR).

Update `installed_versions` passing to new location

---

classes/image_types_ostree.bbclass
classes/image_types_ota.bbclass

Rocko version of this PR: https://github.com/advancedtelematic/meta-updater/pull/385

Don't commit credentials to OSTree repository

---

CONTRIBUTING.adoc

No testing done; documentation only.

CONTRIBUTING.adoc: Add rebasing requirement.

---

classes/image_types_ota.bbclass

Simplify OTA class

---

README.adoc
classes/image_types_ostree.bbclass

Makes it easier to customize ostree commits

Extend ostree support

---

recipes-sota/aktualizr/aktualizr_git.bb

After https://github.com/advancedtelematic/aktualizr/pull/973
tested: built core-image-minimal for qemu

Update aktualizr example secondary config path

---

CONTRIBUTING.adoc
README.adoc
classes/image_types_ostree.bbclass
classes/image_types_ota.bbclass
classes/target_version_example.bbclass

Also includes a small typo fix already in other rocko/sumo PRs.

Feat/ota 627/master/targetversion forwardport

---

README.adoc
classes/image_types_ostree.bbclass

Use OSTREE_COMMIT_BODY write custom text to ostree body
Use OSTREE_COMMIT_SUBJECT to write custom subject
Signed-off-by: Luka Pivk <luka.pivk@toradex.com>

Added support to set custom commit subject and body

---

README.adoc
classes/image_types_ostree.bbclass
recipes-sota/aktualizr/aktualizr-auto-prov.bb
recipes-sota/aktualizr/aktualizr-ca-implicit-prov.bb
recipes-sota/aktualizr/aktualizr-hsm-prov.bb
recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/aktualizr/environment.inc
recipes-sota/aktualizr/files/aktualizr-secondary.service
recipes-sota/aktualizr/files/aktualizr.service

Signed-off-by: Patrick Vacek <patrickvacek@gmail.com>
Passes oe-selftest.

aktualizr: bump to latest for server URL newline fix.

---

lib/oeqa/selftest/cases/updater.py
recipes-sota/aktualizr/aktualizr-ca-implicit-prov-creds.bb
recipes-sota/aktualizr/aktualizr_git.bb

Passes oe-selftest except for an unrelated raspberry pi issue.

aktualizr: Bump to latest and fix names.

---

classes/image_types_ota.bbclass
recipes-sota/aktualizr/aktualizr-ca-implicit-prov-creds.bb

Just trying to be careful and consistent. I didn't change every variable in
places where it seemed like it was obvious that we were dealing with purely
local variables.
Passes oe-selftest.

aktualizr and image_types_ota: more curly braces.

---

recipes-sota/aktualizr/aktualizr_git.bb

Some OSTree improvements, reboot detection, retry failed downloads.

aktualizr: Bump to latest (d00d1a04cc2366d1a5f143b84b9f507f8bd32c44).

---

classes/image_types_ostree.bbclass

Adds initramfs and/or devicetree into checksum calculation.
According to ostree documentation if devicetree and/or initramfs are
included into ostree, checksum should also include them.
This would fix issue #449

classes/image_types_ostree.bbclass: fix checksum calculation

---

README.adoc
classes/sota_raspberrypi.bbclass
recipes-sota/fit-conf/fit-conf.bb

Signed-off-by: Anton Gerasimov <anton.gerasimov@here.com>

Add support for device tree overlays in FIT images

---

recipes-sota/aktualizr/aktualizr_git.bb

Bump aktualizr (thud)

---

recipes-sota/aktualizr/aktualizr_git.bb

Bump aktualizr (sumo)

---

conf/include/bblayers/sota.inc
conf/include/bblayers/sota_am335x-evm.inc
conf/include/bblayers/sota_intel-corei7-64.inc
conf/include/bblayers/sota_m3ulcb.inc
conf/include/bblayers/sota_porter.inc
conf/include/bblayers/sota_qemux86-64.inc
conf/include/bblayers/sota_raspberrypi2.inc
conf/include/bblayers/sota_raspberrypi3.inc
lib/oeqa/selftest/cases/updater.py

Needed for meta-oe since this change:
http://git.openembedded.org/meta-openembedded/commit/?id=987d28c27e70ba12edf2b99745c13e7525206f4a
Note that existing build directories will need to be modified manually!

Add meta-python layer to all platforms

---

recipes-sota/aktualizr/aktualizr_git.bb

Signed-off-by: Mike Sul <ext-mykhaylo.sul@here.com>

Switch to the aktualizr's master head

---

README.adoc
recipes-sota/config/aktualizr-auto-reboot.bb

Signed-off-by: Patrick Vacek <patrickvacek@gmail.com>
Suggested-by: Ben Luck <benjamin.luck@here.com>

README: document auto-reboot config feature.

---

recipes-sota/aktualizr/aktualizr_git.bb

Should be less surprising
Rework of https://github.com/advancedtelematic/meta-updater/pull/505 which didn't quite work on my environment.

Use 'printf' instead of 'echo -e'

---

README.adoc
lib/oeqa/selftest/cases/testutils.py
lib/oeqa/selftest/cases/updater_minnowboard.py
lib/oeqa/selftest/cases/updater_native.py
lib/oeqa/selftest/cases/updater_qemux86_64.py
lib/oeqa/selftest/cases/updater_raspberrypi.py
recipes-connectivity/networkd-dhcp-conf/networkd-dhcp-conf.bb
recipes-sota/aktualizr/aktualizr-auto-prov-creds.bb
recipes-sota/aktualizr/aktualizr-auto-prov.bb
recipes-sota/aktualizr/aktualizr-ca-implicit-prov-creds.bb
recipes-sota/aktualizr/aktualizr-ca-implicit-prov.bb
recipes-sota/aktualizr/aktualizr-hsm-prov.bb
recipes-sota/aktualizr/aktualizr-uboot-env-rollback.bb
recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/aktualizr/files/10-resource-control.conf
recipes-sota/config/aktualizr-auto-reboot.bb
recipes-sota/config/aktualizr-disable-send-ip.bb
recipes-sota/config/aktualizr-log-debug.bb
scripts/qemucommand.py

I've done the logic inside the main aktualizr recipe (as opposed to, another .bb), so that it's easily configurable with `RESOURCE_xxx_pn-aktulizr`, which I find quite handy.

aktualizr resource control

---

classes/sota_raspberrypi.bbclass
conf/include/bblayers/sota_raspberrypi3-64.inc

Also needs change in meta-updater-raspberrypi, forthcoming!
Currently building on master for a final test, as it was initially developed on rocko.

Add support for raspberrypi3-64

---

lib/oeqa/selftest/cases/updater_minnowboard.py

Problem was spotted on sumo and thud #541 and #542 but it should also appear here, in all likelihood. I'll launch a pipeline with minnowboard here soon.

Give more memory for minnowboard selftest

---

README.adoc

Just updating the docs with some helpful missing information.

Doc/ota 2578/logging

---

CONTRIBUTING.adoc

Tests pass: https://main.gitlab.in.here.com/olp/edge/ota/connect/client/meta-updater/pipelines/51509

CONTRIBUTING: mention support for warrior.

---

README.adoc

Caught by @smilingwombat. Oops.

README: fix type in recipe name.

---

recipes-connectivity/connman/connman_%.bbappend
recipes-connectivity/connman/files/0001-tmpfiles-script-do-not-create-the-resolv.conf-symlin.patch
recipes-connectivity/networkd-dhcp-conf/files/clean-connman-symlink.service
recipes-connectivity/networkd-dhcp-conf/files/resolvconf-clean
recipes-connectivity/networkd-dhcp-conf/networkd-dhcp-conf.bb

Connman fix thud

---

recipes-connectivity/connman/connman_%.bbappend
recipes-connectivity/connman/files/0001-tmpfiles-script-do-not-create-the-resolv.conf-symlin.patch
recipes-connectivity/networkd-dhcp-conf/files/clean-connman-symlink.service
recipes-connectivity/networkd-dhcp-conf/files/resolvconf-clean
recipes-connectivity/networkd-dhcp-conf/networkd-dhcp-conf.bb

Connman fix sumo

---

lib/oeqa/selftest/cases/testutils.py
lib/oeqa/selftest/cases/updater_qemux86_64.py

Rough draft, have not tested yet.

Test for setting hwid

---

recipes-sota/aktualizr/aktualizr_git.bb

Depends on ~~https://github.com/advancedtelematic/aktualizr/pull/1243~~ https://github.com/advancedtelematic/aktualizr/pull/1288.

Feat/ota 2666/garage tools mutual tls

---

classes/image_types_ota.bbclass

Expose OSTREE_BOOT_PARTITION in do_image_ota

---

CONTRIBUTING.adoc

Loosely depends on https://github.com/advancedtelematic/updater-repo/pull/31 and https://github.com/advancedtelematic/aktualizr/pull/1325.

Move rocko and sumo to the passive support list.

---

README.adoc

Signed-off-by: Merlin Carter <merlin.carter@here.com>

fixing broken link

---

recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/config/aktualizr-virtualsec.bb
recipes-sota/config/files/30-virtualsec.toml
recipes-sota/config/files/virtualsec.json
scripts/ci/checkout-oe.sh

Useful for updating an arbitrary file in /var.

Example config for a virtual secondary.

---

recipes-sota/aktualizr/aktualizr_git.bb

It was a bit more tricky than I expected due to some bitbake/CMake issue. There might be a cleaner fix, probably on aktualizr side though...

Use proper aktualizr release in deployed images!

---

classes/image_types_ostree.bbclass
recipes-sota/aktualizr/aktualizr_git.bb

Depends on ~~https://github.com/advancedtelematic/aktualizr/pull/1438~~
https://github.com/advancedtelematic/aktualizr/pull/1440

Send a copy of repo manifest through garage-push

---

recipes-sota/aktualizr/aktualizr_git.bb

~~Depends on https://github.com/advancedtelematic/aktualizr/pull/1447.~~

aktualizr: Upgrade to 2019.10 release and latest garage-sign.

---

classes/sota.bbclass
classes/sota_sanity.bbclass

Add sanity checks for user-defined SOTA variables

---

.gitlab-ci.yml

Not completely sure, how you create PRs here.. Let me know if this is correct, then I will create also for other branches and projects

Trigger otf bitbake tests on PR

---

recipes-sota/aktualizr/aktualizr_git.bb

Depends on https://github.com/advancedtelematic/aktualizr/pull/1512

Adapt to shared libraries changes in aktualizr

---

recipes-sota/aktualizr/aktualizr_git.bb

Respin of #659, still depends on https://github.com/advancedtelematic/aktualizr/pull/1512

Adapt to shared libraries changes in aktualizr (bis)

---

recipes-sota/aktualizr/aktualizr_git.bb
recipes-test/demo-config/files/30-fake-pacman.toml
recipes-test/demo-config/files/30-ostree-pacman.toml
recipes-test/demo-config/secondary-config.bb

OTA-4174: Make an ostree update a default on IP Secondary

---

recipes-sota/aktualizr/aktualizr_git.bb

aktualizr: Bump to latest.

---

recipes-sota/aktualizr/aktualizr_git.bb

aktualizr: Bump to 2020.2 release and latest garage-sign

---

recipes-test/demo-config/files/30-ostree-pacman.toml
recipes-test/demo-config/files/30-pacman-config.toml
recipes-test/demo-config/secondary-config.bb

OTA-4388: Conf variable to specify an update type for secondary

---

scripts/qemucommand.py

Remove a debug print in qemucommand.py

---

scripts/ci/checkout-oe.sh

repo cannot do without right now

Manually set a git identity in CI

---

classes/sota_bleeding.inc
scripts/ci/oe-selftest.sh

I'm a bit surprised we never noticed this was missing!

sota_bleeding: Also set aktualizr-native to the latest.

---

recipes-sota/aktualizr/aktualizr_git.bb

Update garage-sign to the latest as well.

aktualizr: Update to 2020.3 release.

---

recipes-sota/aktualizr/files/aktualizr-secondary.service
recipes-sota/aktualizr/files/aktualizr.service

fix: run aktualizr service after network is online

---

lib/oeqa/selftest/cases/testutils.py
recipes-sota/aktualizr/aktualizr_git.bb

Depends on https://github.com/advancedtelematic/aktualizr/pull/1613.

aktualizr: Bump to latest along with garage-sign.

---

conf/layer.conf

layer.conf: update LAYERSERIES_COMPAT for dunfell

---

scripts/envsetup.sh

Well, we never promised it would work with zsh, but this should fix it.
As bash array were not bad enough, zsh has to do it differently... :cry:

Fix envsetup when run in zsh

---

recipes-sota/aktualizr/files/10-resource-control.conf

This allows you to see how much bandwidth was used with `systemd status aktualizr`.

aktualizr: Use systemd IP accounting.

---

classes/image_types_ostree.bbclass
recipes-sota/aktualizr/aktualizr_git.bb

Bump aktualizr to 2020.7 revision

---

recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_0.0.1.bb

Signed-off-by: antznin <agodard@witekio.com>

ostree-kernel-initramfs: deploy dtbs from OSTREE_DEVICETREE

---

classes/image_types_ostree.bbclass

I'm pretty sure chown makes no sense here...

image_types_ostree: fix chmod

---

classes/image_types_ostree.bbclass
classes/sota.bbclass
recipes-sota/aktualizr/aktualizr_git.bb
recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_0.0.1.bb

Signed-off-by: Anatoliy Odukha <aodukha@gmail.com>

aktualizr: Upgrade dunfell to 2020.10 release

---

recipes-sota/aktualizr/aktualizr-device-prov-hsm.bb
recipes-sota/aktualizr/aktualizr-device-prov.bb
recipes-sota/aktualizr/aktualizr-shared-prov.bb
recipes-sota/aktualizr/aktualizr_git.bb

aktualizr: Upgrade to 2020.9 release.
Signed-off-by: Anatoliy Odukha <aodukha@gmail.com>

aktualizr: Upgrade to 2020.10 release

---

classes/image_types_ota.bbclass

Reverts advancedtelematic/meta-updater#790 because of error on boot

Revert "[dunfell] Fix ota-ext4 IMAGE_FSTYPE"

---

scripts/ci/Dockerfile.bitbake
scripts/ci/Dockerfile.checkout

This should hopefully resolve some python3/repo issues.

Update dockerfiles to use Debian Buster.

---

conf/layer.conf

layer.conf: update LAYERSERIES_COMPAT for hardknott

---

recipes-sota/ostree/ostree_git.bb

Signed-off-by: Stephan Eberle <stephaneberle9@gmail.com>

Fixed outdated OSTree branch reference (#817)
