conf/distro/sota.conf.inc
OSTree can't currently work without systemd (to my knowledge, some more research can be done here) so we have to make this mandatory.
=> Add systemd DISTRO_FEATURE for OSTree

conf/distro/sota.conf.inc
We may/should probably investigate the possibility of running OSTree without systemd and initramfs.
=> Set systemd as the chosen init manager

recipes-sota/rvi-sota-client/rvi-sota-client_git.bb
It's required for OSTree updates and I've lost it somewhere in merging process earlier.
=> Bring sota_ostree.sh back

recipes-sota/rvi-sota-client/rvi-sota-client_git.bb
For posterity: this bump is to make the systemd service specify the location of sota_certificates and the package manager on the command line. This was requested so that buildsrv on ATS Garage doesn't have to spit out config files with a bunch of different locations depending on the target system.
=> update sota client version for new systemd.service

recipes-sota/sota-client-cpp/sota-client-cpp_git.bb
Update the version of SOTA client C++ to the
latest version from 25 Jan 2017.
=> sota-client-cpp: Update version

recipes-sota/rvi-sota-client/rvi-sota-client_git.bb
I've run into this bug while trying to update rvi-sota-client in AGL's meta-sota, not sure if it is reproducible in meta-updater.
=> Add lazycell create (required by mio)

recipes-support/lshw/files/ldflags.patch, recipes-support/lshw/lshw_02.16.bb
The bug was found when building against Yocto morty, but won't hurt having it in Krogoth as well.
=> Fix a bug with missing GNU_HASH in lshw under Yocto

conf/include/local/sota_bleeding.inc, recipes-sota/aktualizr/aktualizr_git.bb
This overrides the package version for Aktualizr to be latest master. This is
recommended for development and test only.  To use it, add the following to
local.conf:
require conf/include/local/sota_bleeding.inc
=> Create sota_bleeding.inc config file to build against master

recipes-sota/ostree/ostree_git.bb
OSTree has a hardcoded path to ostree-grub-generator, this wrapper sets it
dynamically to avoid problems with sharing a SSTATE cache.
=> Create a wrapper so OSTree can find ostree-grub-generator

conf/distro/sota.conf.inc, scripts/envsetup.sh
Setting the default DISTRO to include systemd means that the rvi-sota-client
starts by default, making it work 'out of the box'.  image-prelink seems to be
broken at the moment, so I've disabled it by default.
=> Set default DISTRO, disable prelink

conf/include/local/sota_minnowboard.inc, recipes-sota/ostree-initrd/files/init.sh, recipes-sota/ostree-initrd/ostree-initrd.bb
Support identifying the root filesystem via a kernel command line like
'ostree_root=LABEL=mylabel'. Also make it mount a filesystem labeled 'otaroot'
by default.
This means it is possible to test the Minnowboard build in Qemu.
=> Mount the root filesystem by label rather than path

conf/distro/poky-sota-systemd.conf, conf/distro/sota.conf.inc
sota-client is optional for external projects, such as AGL, build it only if using our own envsetup
=> Move rvi-sota-client to poky-sota-systemd.conf

classes/sota_am335x-evm-wifi.bbclass
Even when VIRTUAL-RUNTIME_net_manager is set to "systemd", connman rewrites /etc/resolv.conf
=> Disable connman, systemd-networkd is used instead

recipes-sota/aktualizr/aktualizr_git.bb
To use it as a replacement to rvi_sota_client we're still missing a systemd service and proper "certificates_path" in sota.toml. I would suggest to wait until autoprovisioning goes production.
=> Build aktualizr with OSTree support enabled

conf/distro/poky-sota-systemd.conf, conf/distro/poky-sota.conf, conf/distro/sota.conf.inc
Pull the common lines from the poky-sota.conf and poky-sota-systemd.conf
example distributions into a separate include file that can be pulled into
other environments.
This might be by including it in a user's own custom distro, or by directly
including it in local.conf (e.g. AGL).
require conf/distro/sota.conf.inc
=> Extract common distro configuration into sota.conf.inc

classes/sota.bbclass
As a temporary fix, treehub is going to use this to derive the relevant
hardwareIdentifier for a push.
=> Prefix OSTREE_BRANCHNAME with ${MACHINE}-

classes/image_types_ota.bbclass, recipes-sota/aktualizr/aktualizr_git.bb, recipes-sota/aktualizr/files/aktualizr-manual-provision.service
Aktualizr currently supports OSTree updates in non-autoprovisioned mode. Add a
systemd service to run it in that mode. It uses the same location for the
config file as rvi-sota-client (/sysroot/boot/sota.toml)
Also, the aktualizr recipe is reformatted according to
meta-openembedded/contrib/oe-stylize.py (which follows the OE styleguide)
=> Support Aktualizr in manual-provisioning mode

classes/sota.bbclass, conf/distro/poky-sota-systemd.conf, conf/distro/sota.conf.inc
Client can be changed to the rust one by adding 'SOTA_CLIENT = "rvi-sota-client"' to local.conf
=> Add option to choose which sota client to use (if any)

classes/sota.bbclass, conf/distro/sota.conf.inc
In some use cases (etc. AGL) we don't include sota.conf.inc which will result in unset SOTA_CLIENT. Surprisingly, unset variables ARE NOT resolved to empty strings by bitbake, so the build fails in these cases.
=> Set default SOTA_CLIENT directly in sota.bbclass

recipes-core/images/initramfs-ostree-image.bb
AGL sets this to 500MB to allow extra space in the default image.  Set it to 0
in the initramfs.
=> Override IMAGE_ROOTFS_EXTRA_SPACE

classes/image_types_ostree.bbclass
The creation of images, such as rpi-basic-image failed
on branch Pyro due to missing/wrong path to unzip.
This patch ensures that unzip is called with its
full path from the bindir.
=> image_types_ostree.bbclass: Fix path to unzip

recipes-sota/rvi-sota-client/rvi-sota-client_git.bb
Petname usage got inadvertently removed a few commits ago, but nobody
noticed. We need the petnames because otherwise attempting to reprovision
a device will fail. This is a one-commit version bump to solve that problem.
=> PRO-3157 Restore petname usage in rvi-sota-client provision script

recipes-bsp/u-boot/u-boot_2016.11.bb
In pyro, u-boot-common_2017.01.inc is created. In the inc file,
SRC_URI and LICENSE are defined. So u-boot_2016.11 needs those variables
Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>
=> Add LICENSE and SRC_URI variable in recipe

recipes-support/glib-networking/glib-networking_%.bbappend
Revert the change from 24 Jul and add again the
hackery which removes removes pkgconfig.
=> glib-networking_%.bbappend: Add again hackery

recipes-core/images/initramfs-ostree-image.bb
Set
IMAGE_OVERHEAD_FACTOR = "1.0"
Otherwise the initrd was 12M due to the default overhead (x1.3).
=> Set IMAGE_OVERHEAD_FACTOR for fixed initrd size

recipes-sota/ostree/ostree_git.bb
Move Yocto/OE recipe xz from the run-time dependencies
to the dependencies because liblzma is required for
the successful configuration of OSTree.
=> ostree_git.bb: Depends on xz for liblzma

scripts/envsetup.sh
Use the configurations for local.conf provided by
layer meta-updater-* (depending on the machine)
if variable TEMPLATECONF has not been set.
Otherwise, if the variable is not set or if the
layer does not provide any configurations then
the default will be used (just as before this change).
=> scripts/envsetup.sh: Use machine specific local.conf

classes/image_types_ostree.bbclass
Print warnings if variable SOTA_PACKED_CREDENTIALS
is not set or if the specified file does not exist.
=> Show warnings if credentials are not provided

classes/image_types_ostree.bbclass
We need to make sure 'sync' is in place.
Unzip-native could probably also use ":do_populate_sysroot".
=> Pyro needs coreutils-native (we call sync) b/c rss

classes/sota.bbclass, recipes-sota/aktualizr/aktualizr_git.bb, recipes-support/glib-networking/glib-networking_%.bbappend, recipes-support/sc-hsm-embedded/files/0001-Cross-compilation-tweaks.patch, recipes-support/sc-hsm-embedded/sc-hsm-embedded_git.bb, recipes-support/softhsm-testtoken/files/createtoken.service, recipes-support/softhsm-testtoken/files/createtoken.sh, recipes-support/softhsm-testtoken/softhsm-testtoken.bb, recipes-support/softhsm/files/0001-Cross-compilation-tweaks.patch, recipes-support/softhsm/softhsm_git.bb
Also introduces SOTA_CLIENT_FEATURES variable which should control client's functionality. E.g. SOTA_CLIENT_FEATURES = "hsm hsm-test" to add HSM support and create a mock HSM token for testing.
HSM support inside aktualizr itself is coming once tested.
=> Add recipes to test pkcs11 functionality in Aktualizr

classes/image_types_ostree.bbclass
Quick fix to maybe make @OYTIS's life easier.
I recommend pointing the necessary variables to the output directory created from running cert_provider with -d so that you can quickly regenerate the credentials at will.
I also recognize that I may have put this change in a less than ideal location. Please advise if there is a better organizational strategy. I'm still learning this side of things.
=> Hacky ability to provide client credentials and install them on the device

classes/sota.bbclass, recipes-sota/aktualizr/aktualizr-hsm-test-prov.bb, recipes-sota/aktualizr/aktualizr_common.inc, recipes-sota/aktualizr/aktualizr_git.bb, recipes-sota/aktualizr/files/sota_hsm_test.toml, recipes-sota/ostree/ostree_git.bb, recipes-support/softhsm-testtoken/files/createtoken.sh
Credentials triple (client.pem, pkey.pem, root.crt) should be placed in /var/sota/token after the build or on the running image. A convenient way to do it is by using cert_provider:
```
aktualizr_cert_provider -r -c /path/to/credentials -d /path/to/var/sota/token
```
=> Support pkcs#11 in aktualizr and add softhsm token for testing

classes/sdcard_image-rpi-ota.bbclass
Branch name can be misleading, because the PR doesn't cover the initramfs case, we need to collect more info to fix that.
=> Remove IMAGEDATESTAMP to make sstate input deterministic

recipes-sota/ostree-initrd/files/init.sh
=> Share /run directory between initramfs and system image to communicate ostree-booted file

classes/sdcard_image-rpi-ota.bbclass
Branch name can be misleading, because the PR doesn't cover the initramfs case, we need to collect more info to fix that.
=> Remove IMAGEDATESTAMP to make sstate input deterministic (morty)

recipes-sota/ostree/ostree_git.bb
Unnecessary error messages have been silenced by skipping some checks
that weren't necessary in our case.
=> Bump ostree version to get Shaun's fix.

classes/image_repo_manifest.bbclass, classes/sota.bbclass
Helpful for debugging, etc.
Mostly copied from here:
https://github.com/openivimobility/meta-oim/blob/master/classes/image-repo-manifest.bbclass
Does not require repo to be installed on the host. If it isn't, the manifest simply isn't copied. Although if you're using meta-updater, you probably should have repo...
=> Copy repo manifest to the device.

scripts/run-qemu-ota
Running qemu while overlay is being created is bad.
=> Fix race condition in run-qemu-ota

recipes-sota/aktualizr/aktualizr-hsm-test-prov.bb, recipes-sota/aktualizr/aktualizr_git.bb
hsm-test feature requires aktualizr-hsm-test-prov in order to work properly and vice versa, so it's basically useless.
=> Delete hsm-test SOTA_CLIENT_FEATURE as redundant and provoking mistakes

classes/sota_qemux86-64.bbclass, scripts/envsetup.sh
Also add IMAGE_ROOTFS_EXTRA_SPACE to qemu configuration which was
the original motivation for returning TEMPLATECONF processing (see
https://github.com/advancedtelematic/meta-updater-qemux86-64/pull/9 )
=> Ignore configuration templates to avoid duplicate inclusion of stuff

classes/image_repo_manifest.bbclass
The repo tool searches up the directory tree to find the .repo directory.
Cleanly handle the case where it can't find anything.
=> Fix builds outside the .repo directory

recipes-sota/aktualizr/aktualizr_git.bb
Under some conditions missing space can lead to a corrupted environment variable
=> Add spaces before "_append" clauses

classes/image_types_ota.bbclass
calculate_size had a typo that made one of the cases fail.  This patch fixes it.
=> Fix calculate_size in case $SIZE < $MIN

recipes-sota/aktualizr/aktualizr-auto-prov.bb
The directory is required by environment.inc
=> Always create /usr/lib/sota in autoprov recipe

recipes-sota/aktualizr/aktualizr-auto-prov.bb
If not using SOTA_PROVISIONING_CREDENTIALS, nothing is written to /var/sota but it is still created. Quick fix: install it.
We could instead not create /var/sota at all, but since we seem to use it all the time, it's not a bad thing just to make it and leave it empty.
I also fixed an issue where we were doing the same thing in both the if and else clause. DRY.
This issue was found by @jochenschneider and hopefully fixes all his troubles.
=> Install /var/sota.

lib/oeqa/selftest/updater.py, recipes-sota/aktualizr/aktualizr-auto-prov.bb, recipes-sota/aktualizr/aktualizr-hsm-test-prov.bb, recipes-sota/aktualizr/aktualizr-implicit-prov.bb, recipes-sota/garage-sign/garage-sign.bb, recipes-support/ca-certificates/ca-certificates_%.bbappend
* hsm-test is no longer used.
* Use Yocto variables where suitable.
* Eliminate redundant directory slashes.
=> Minor fixes and cleanup.

recipes-sota/aktualizr/credentials.inc
Reported by Stevan, traced to the problem by me, actually fixed by Anton.
Note that this does NOT entirely fix bitbaking for implicit provisioning without `SOTA_PACKED_CREDENTIALS`.
=> Fix variable expansion problem when SOTA_PACKED_CREDENTIALS is not set.

recipes-sota/aktualizr/aktualizr-implicit-prov.bb
This basically cripples implicit provisioning but at least it bitbakes
without error.
=> Don't run implicit_writer if SOTA_PACKED_CREDENTIALS is not set.

recipes-sota/aktualizr/aktualizr_git.bb
Not ready yet since we will also want to bump the aktualizr version once https://github.com/advancedtelematic/aktualizr/pull/437 is merged.
=> Properly install example-interface on target and remove it on host.

classes/sota_qemux86-64.bbclass
Use u-boot-ota recipe for QEMU x86-64 bootloader.
=> sota_qemux86-64.bbclass: Use u-boot-ota

COPYING.MIT
Many other Yocto layers are alse under the MIT license, so this matches what
people will likely expect. For example meta-rust, meta-ti, meta-raspberrypi are
all MIT licensed.
=> Add MIT license to recipe metadata

README.adoc
Not relevant to the user, as per PRO-4483
=> Remove OSTREE_BRANCHNAME mention in README

recipes-sota/aktualizr/aktualizr-implicit-prov.bb, recipes-sota/aktualizr/aktualizr_git.bb
Also remove `--no-root-ca` for implicit prov. It's still there for the HSM case. If we really do need that flag for the implict recipe for Spekulatius, then we need to do some thinking.
=> Bump aktualizr to get open source server CA fix.

recipes-support/sqlite/sqlite3_3.14.1.bbappend, scripts/envsetup.sh
Backport some pyro fixes to morty to fix issues around pseudo.
First, sqlite needs to be built with -fPIC on some systems to make linking it with pseudo-native work.
Second, in some installations, pseudo-native would fail because of a previously backported patch getting doubly applied. The problem was some cleverness in envsetup.sh that accidentally created duplicate layers.
=> Bugfix/pro 4632/morty pseudo bugs

classes/sota_raspberrypi.bbclass, conf/include/bblayers/sota_raspberrypi2.inc, conf/include/bblayers/sota_raspberrypi3.inc
Add Yocto/OE layer meta-python to bblayers as it
required for building recipe rpi-gpio for Yocto/OE
layer meta-raspberrypi.
=> sota_raspberrypi*.inc: Included meta-python

classes/sota_minnowboard.bbclass
Additionally don't create extra images to save space and not confuse the user
=> Deploy startup.nsh before composing flashable image

recipes-sota/ostree/ostree_git.bb
Cherry-picked from rocko. Should save some headaches.
This should be unnecessary, but for some reason isn't.
=> Add PR = "1" to ostree to fix annoying caching problem.

classes/image_types_ostree.bbclass, classes/image_types_ota.bbclass
A bit hacky method, but OSTree refhash is only known to image_types_ostree and image_types_ota bbclasses, so I couldn't figure out a better one.
I couldn't test it on staging yet, where it has most sense, but on prod it seems to send a reasonable manifest.
Should work with SQLite as well, because of how FS->SQL migration works (and yes, it's also a hack).
Making a PR to pyro, we'll have to merge a couple of things again when we make the final transition to rocko.
=> Deploy initial primary version information

recipes-sota/aktualizr/aktualizr_git.bb
As of 6c0dd6c87f4f4027e9b89f9a9e0dc12ef386d39d these are installed with a
normal 'make install' (via cmake)
=> Remove manual installation of /usr/lib/sota/schemas

recipes-bsp/grub/grub-efi_%.bbappend
grub-efi from oe-core now includes configfile in the default buildin
modules list.
=> grub-efi: remove bbappend as change is now provided by oe-core

recipes-sota/ostree/ostree_git.bb
Fix the following boot warning:
systemd[1]: Configuration file /usr/lib/systemd/system/ostree-remount.service
is marked executable. Please remove executable permission bits. Proceeding
anyway.
=> ostree: fix systemd service files permission

recipes-sota/aktualizr/aktualizr_git.bb
This was needed for GENIVI support, which got dropped recently
=> Remove aktualizr's jansson dependencies

README.adoc, lib/oeqa/selftest/cases/updater.py, recipes-sota/aktualizr/aktualizr_git.bb, recipes-support/libp11/libp11_0.4.7.bb
Merge pyro into rocko. This brings in a bunch of work on oe-selftest. There are some minor differences for rocko, but most of the logic is the same. The ovmf patch has been omitted since the fix was upstreamed in rocko.
=> Test/pro 4481/hsm rocko

classes/sota_raspberrypi.bbclass
To be tested together with https://github.com/advancedtelematic/meta-updater-raspberrypi/pull/17
Kernel parameters are still non-updateable, for which I can imagine two possible solutions:
1. Build device tree overlay containing command line options as a bitbake artifact. The problem with this approach is that bitbake's infrastructure is created to build all the device trees from the kernel source tree, so every kernel will need a patch adding our overlay before build.
2. Add kernel command line to OSTree pretty much the same way as kernel, initramfs and dtb work today.
There is another problem with u-boot passing extra parameters to kernel via /chosen/bootargs in the device tree overwriting whatever was there before. That may be not the behaviour expected by the user, who wants them to …
=> Use FIT image on RPi

classes/image_types_ota.bbclass
/boot/grub2/grub.cfg should reflect the grub.cfg used by the boot process
instead of being an empty file.
uEnv.txt should have a similar logic, but will get to that once I'm sure it will not cause any regression.
=> image_types_ota: make default grub.cfg a link to loader/grub.cfg

scripts/lib/wic/canned-wks/sdimage-sota.wks
image_types_ota already defines the rootfs label when creating the ota
image, so drop label overwrite when creating the sdcard partition.
=> sdimage-sota.wks: remove label as it gets set by image_types_ota

classes/image_types_ostree.bbclass
Avoid exposing the sign repo after the build is completed.
=> image_types_ostree.bbclass: clean up GARAGE_SIGN_REPO after push

classes/sota_qemux86-64.bbclass
The mentioned issue doesn't seem to exist anymore
=> Stop forcing Linux 4.4 on qemux86-64

classes/image_types_ostree.bbclass, classes/sota.bbclass
Both values can be defined by the user, allowing a custom version id and
URL, which is specially useful for CI builds.
=> Add support for custom garage target version and url

recipes-sota/aktualizr/aktualizr_git.bb
Provide the default sota configs as part of host-tools so they can be used by aktualizr_cert_provider and aktualizr_implicit_writer.
This pull request depends on #284.
=> aktualizr: include default configs as part of host-tools

recipes-sota/ostree/ostree_git.bb
Python is not needed by ostree itself (no script or utility using
python), so remove it from the rdepends list.
=> ostree: remove python from rdepends

conf/layer.conf
Allows the user to easily identify if the layer is compatible with
oe-core.
=> layer.conf: add LAYERSERIES_COMPAT markup

classes/image_types_ota.bbclass
Make sure to use the custom target version when creating
installed_versions if defined by the user.
=> Check for custom target version for installed_versions

recipes-sota/config/aktualizr-disable-send-ip.bb, recipes-sota/config/aktualizr-example-interface.bb, recipes-sota/config/aktualizr-log-debug.bb, recipes-sota/config/files/30-disable-send-ip.toml, recipes-sota/config/files/30-example-interface.toml, recipes-sota/config/files/90-log-debug.toml
This is more reliable and readable than just dumping things with echo. Plus it
is easier for setting permissions, and it fixes some obscure problem with line
endings that only happens on shovel.
=> Put extra configs in their own files.

recipes-sota/ostree/ostree_git.bb
The only reason we needed it was because of a relative path that I've now made absolute.
This may fix the problem at the root of https://github.com/advancedtelematic/meta-updater/pull/318.
=> ostree: Don't use autotools-brokensep.

recipes-sota/ostree/ostree_git.bb
Recipe cleanup, containing:
- fix license description
- reduce amount of local customizations
- remove need for native specific dependencies
- break up into more packages (reduce runtime dependency list when only ostree is required)
=> Ostree recipe cleanups

classes/image_types_ostree.bbclass
Make garage-push logs more useful in case of errors when pushing to the
OTA+ server.
=> garage-push: enable verbose logging by default

classes/sota_raspberrypi.bbclass, recipes-sota/aktualizr/aktualizr-uboot-env-rollback.bb, recipes-sota/aktualizr/aktualizr_git.bb, recipes-sota/aktualizr/files/aktualizr.service
* Added ubootenv client features that pulls respective configuration snippet
* Allowed aktualizr to run even if there is no network connection. It can pollute the log somewhat, but will let aktualizr acknowledge successful boot even if there is no internet connection. An alternative solution would be to implement yet another binary to acknowledge the boot.
* Aktualizr recipe now points to PR branch to test before merging.
=> Add support for rollback on Raspberry Pi

scripts/ci/Jenkinsfile, scripts/ci/build.sh, scripts/ci/configure.sh, scripts/ci/local.conf.append
- check out meta-updater and read the Jenkinsfile
- check out aktualizr
- use repo to checkout everything needed for an image build
- move repo's meta-updater commit to the one that triggered CI
- build core-image-minimal
With these properties:
- keep existing workspace between run, so that builds are naturally cached. It might need manual clean intervention sometimes
- a build is triggered when a commit is pushed on aktualizr master, meta-updater master or any branch of a git tracked by repo
=> First pipeline setup for meta-updater CI

classes/image_types_ostree.bbclass
The boot/loader folders are only required at the deploy stage, which is
already created by image_types_ota.bbclass.
=> image_types_ostree: no need to create boot/loader folders when creating ostree repo

classes/image_types_ota.bbclass, classes/sota.bbclass
advancedtelematic/meta-updater#342
Added variable `BUILD_OTA_TARBALL` that when set to "1" will create a tarred output of the ota image in addition to the ext4 output. So, when set _lmp-gateway-image.otaimg_ and _lmp-gateway-image.ota.tar_ are produced from the build. 
This
=> Support for creating an otaimg.tar file in addition to the ext4 image

recipes-sota/ostree/ostree_git.bb
Upgrade OSTree to a git revision ahead of the v2018.7 release in order
to include additional memory leak fixes.
Upstream release notes since v2017.13+:
- https://github.com/ostreedev/ostree/releases/tag/v2017.14
- https://github.com/ostreedev/ostree/releases/tag/v2017.15
- https://github.com/ostreedev/ostree/releases/tag/v2018.1
- https://github.com/ostreedev/ostree/releases/tag/v2018.2
- https://github.com/ostreedev/ostree/releases/tag/v2018.3
- https://github.com/ostreedev/ostree/releases/tag/v2018.4
- https://github.com/ostreedev/ostree/releases/tag/v2018.5
- https://github.com/ostreedev/ostree/releases/tag/v2018.6
- https://github.com/ostreedev/ostree/releases/tag/v2018.7
=> ostree: upgrade to v2018.7+

lib/oeqa/selftest/cases/updater.py, recipes-sota/aktualizr/aktualizr_git.bb
Work around a bug in oe-selftest with migration and aktualizr-info
interplay by forcing --allow-migrate for now.
=> aktualizr: bump to latest for key rotation and storage updates (sumo)

lib/oeqa/selftest/cases/updater.py, recipes-sota/aktualizr/aktualizr_git.bb
Work around a bug in oe-selftest with migration and aktualizr-info
interplay by forcing --allow-migrate for now.
=> aktualizr: bump to latest for key rotation and storage updates (master)

scripts/qemucommand.py
I'm not sure which cpu type QEMU picks if it's not specified, but I was getting a warning
`qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]`
With -cpu host option it will use only supported features and no warning is produced.
=> Specify cpu type -host- for KVM mode

recipes-support/openct/openct_%.bbappend
This has now been upstreamed to meta-openembedded.
=> openct: remove unnecessary bbappend.

README.adoc
Apparently linebreaks matter.
No testing done; documentation only.
=> Fix README formatting.

README.adoc, classes/image_types_ota.bbclass, lib/oeqa/selftest/cases/updater.py, scripts/lib/wic/plugins/source/otaimage.py, scripts/qemucommand.py
do_image tasks should not access `DEPLOY_DIR_IMAGE` directly. The `IMGDEPLOYDIR` is properly sstate managed and allows to use the symlinking feature of OpenEmbedded.
To make use some of the features the file ending need to match the image fstype name. That requires us to rename `.otaimg` to `ota-ext4`. This also makes sure that the image is named such that it can be extended to support other file systems etc.
=> Use IMGDEPLOYDIR

lib/oeqa/selftest/cases/updater.py, recipes-sota/aktualizr/aktualizr_git.bb
Bump to the latest version as well.
Passes oe-selftest.
=> aktualizr: Remove implicit_writer. It is now unused.

README.adoc, classes/image_types_ostree.bbclass, classes/image_types_ota.bbclass, classes/target_version_example.bbclass
Making a PR to rocko first because the primary user for that is Spekulatius.
Turns out there is no way to set a bitbake variable from a shell task, so I was choosing between writing a hacky python task calling git via `os.popen()` and adding a hack to `image_types_ostree.bbclass` to read version from a file. The latter seemed cleaner to me.
=> Provide example for setting UPTANE target version automatically

classes/image_types_ostree.bbclass
The OSTree repository might be shared accross several individual
OSTree builders. Use bitbakes lockfiles mechanism to lock the
OSTree for exclusive use.
=> classes: image_types_ostree: use locking during OSTree repo update

classes/image_repo_manifest.bbclass
buildinfo function name is used in poky:
meta/classes/image-buildinfo.bbclass
Both classes could not be used together
=> Fix function name conflict

CONTRIBUTING.adoc, README.adoc, scripts/find_aktualizr_dependencies.sh
Also remove all references to aktualizr-example-interface. It has been removed.
=> docs: better explanation of oe-selftest requirements.

lib/oeqa/selftest/cases/updater.py
The qemucommand.py script uses kvm-ok to determine whether KVM
is available. However, kvm-ok is very Ubuntu specific and not
readily available on Fedora.
Use QEMU_USE_KVM variable which is also used in OpenEmbedded
selftests. The variable must contain True to enable KVM for
machines containing x86 in its name, or contain a list of
machines. For meta-updater this makes sure KVM is used for all
tests:
QEMU_USE_KVM = "intel-corei7-64 qemux86-64"
=> selftest: introduce QEMU_USE_KVM

README.adoc, classes/image_types_ostree.bbclass, classes/sota.bbclass, recipes-sota/aktualizr/aktualizr_git.bb
I was able to build image with custom hardware id.
Image has been successfully provisioned and appeared in the web admin panel.
Also Image successfully has been updated to a new version of image.
=> Allow setup custom hardware_id

classes/image_types_ota.bbclass
Curly braces are necessary around bitbake variables
Signed-off-by: Anton Gerasimov <anton.gerasimov@here.com>
=> Fix bloated OTA image

classes/image_types_ostree.bbclass
OSTree does not allow concurrent access to the repository. If
two bitbake instances use the same OSTree repository, then they
might access it simultanously. The lockfile to prevent such
simultaneous access should really be in the same location where
the OSTree repository is stored.
Revert back to the location inside the OSTree repository.
Fixes: e97975d6113c ("image_types_ostree/ota.bbclass: refactor ostree task")
=> image_types_ostree: use OSTree repo location for lockfiles

classes/image_types_ostree.bbclass, conf/distro/sota.conf.inc, lib/oeqa/selftest/cases/updater.py
This makes use of the OpenEmbedded feature usrmerge, which implements usrmove at recipe build/package time. We build with usrmerge DISTRO_FEATURE since quite some time, and have not seen a downside here.
=> Use usrmerge

recipes-sota/ostree/ostree_git.bb
Update libostree to the v2018.9 release.
Upstream release notes since v2018.7:
- https://github.com/ostreedev/ostree/releases/tag/v2018.8
- https://github.com/ostreedev/ostree/releases/tag/v2018.9
=> ostree: upgrade to v2018.9

classes/image_types_ostree.bbclass
We remove GARAGE_SIGN_REPO at the start and end of this task, which
causes trouble if two images call this task at the same time. This
probably could be fixed in a better fashion (like putting the repo in an
image-specific subdirectory) but this is quick and easy, and the task
usually doesn't take long to run, so the lack of parallelization is not
a big loss.
=> image_garagesign: Use a lock to fix concurrency problems.

classes/image_types_ota.bbclass
That is the new name used in master since f07be1805cc22b5428ff529b705731360b485d06
I did not run any test yet, need to warm up my rocko builds again...
Also for rocko: #457
=> (sumo) Add .ota-ext4 image symlink

classes/image_types_ota.bbclass
That is the new name used in master since f07be1805cc22b5428ff529b705731360b485d06
I did not run any test yet, need to warm up my rocko builds again...
=> (rocko) Add .ota-ext4 image symlink

lib/oeqa/selftest/cases/updater.py, recipes-sota/aktualizr/aktualizr_git.bb
- OStree installations are considered complete after a reboot under the new version
- image downloads are not parallelized anymore
- various enhancements and bug fixes
oe-selftests are currently running
=> aktualizr: bump to latest 1cad6d10286ade64b24021ca0e23de0d3b64f520

conf/distro/sota.conf.inc
Use reproducible builds by default. OSTree sets mtime to 0 at
commit time anyway. This makes sure that all mtime timestamps
are 0 already at build time. This is relevant for programs
which relies on mtime of deployed artifacts at runtime.
Python for instance writes the mtime of the source file into
bytecode files (pyc) at build time. When OSTree then clears
the mtime Python considers all bytecode files as stale.
Reproducible binaries also avoid unnecessary differences
between two OSTree commits. E.g. if the sstate cache is
cleared between two OSTree commits OpenEmbedded might create
slightly different binaries.
Note however that not all all recipe generate reproducible
binaries at this time.
This addresses #461.
=> sota.conf: use reproducible builds by default

classes/sota.bbclass
A regression was introduced by commit 9dcfcdb9:
[ classes, images: Use standard variables for initramfs ]
it replaced OSTREE_INITRAMFS_IMAGE with INITRAMFS_FSTYPES which is
fine, but the '??=' should be changed to "?=" as well, or else it will
not take effect since INITRAMFS_FSTYPES's already set in bitbake.conf
with '?='.
=> sota.bbclass: fix a variable assignment regression

recipes-sota/aktualizr/aktualizr_git.bb
To 2aa9d93ccea09ec327789eecf858de561ef632da, which changed the installation result reporting format
=> Bump aktualizr (master)

recipes-sota/aktualizr/aktualizr_git.bb
To 2aa9d93ccea09ec327789eecf858de561ef632da, which changed the installation result reporting format
=> Bump aktualizr (rocko)

recipes-sota/aktualizr/aktualizr-auto-prov-creds.bb
It will only be used by garage-sign.
See https://github.com/advancedtelematic/ota-plus-server/pull/1913.
=> aktualizr-auto-prov-creds: remove API Gateway URL if it exists.

classes/image_types_ostree.bbclass, classes/image_types_ota.bbclass
To enable simultaneous bitbaking of two images with the same branch name, create
a new ref in the OSTree repo using the basename of the image.
As @OYTIS has pointed out, this probably won't solve every problem that might
come up with simultaneous bitbaking, such as if the two images use different
bootloaders. However, it does solve the immediate problem that comes up with our
primary-image + secondary-image example.
=> image_types_ostree: Add a unique ref to fix simultaneous bitbaking.

lib/oeqa/selftest/cases/updater.py
It was a nice idea when we were less confident about bitbaking and
oe-selftest, but at this point, it is redundant and provides no useful
information while adding extraneous time to the already long test suite.
=> Remove add package test

recipes-sota/aktualizr/aktualizr-ca-implicit-prov-creds.bb, recipes-sota/aktualizr/aktualizr-ca-implicit-prov.bb
When SOTA_DEPLOY_CREDENTIALS got introduced deployment of the
provisioning credientials has been moved to
aktualizr-ca-implicit-prov-creds. Move the warning accordingly.
=> Move warning about insecure practise to the correct recipe

recipes-sota/aktualizr/aktualizr-auto-prov.bb, recipes-sota/aktualizr/aktualizr-hsm-prov.bb, recipes-sota/aktualizr/aktualizr-uboot-env-rollback.bb, recipes-sota/ostree/ostree_git.bb
Several recipes had ${STAGING_DIR_NATIVE}${libdir}, which won't
work if ${libdir} != ${libdir_native}.
Signed-off-by: Corey Minyard <cminyard@mvista.com>
=> aktualizr: Use ${libdir_native} when referring to native files

README.adoc, classes/sota_am335x-evm-wifi.bbclass, classes/sota_m3ulcb.bbclass, classes/sota_minnowboard.bbclass, classes/sota_porter.bbclass, classes/sota_qemux86-64.bbclass, classes/sota_raspberrypi.bbclass, conf/distro/poky-sota-systemd.conf, conf/distro/poky-sota.conf, recipes-connectivity/connman/connman_%.bbappend, recipes-connectivity/networkd-dhcp-conf/files/20-wired-dhcp.network, recipes-connectivity/networkd-dhcp-conf/networkd-dhcp-conf.bb, recipes-test/images/secondary-image.bb
connman is an annoying dependency which is not present in the base poky distribution.
The first step is to remove it from default poky-sota.conf and add it back on the various machines that we have.
The second step is to replace it with a simple systemd-networkd configuration on qemux86-64. We can migrate other platforms later.
One notable change is that users of the layer without systemd won't have a default network configuration on qemux86-64 but:
* we don't test anything without systemd
* users are expected to know better about their network configuration requirements than us
One even less intrusive alternative would be to add the `IMAGE_INSTALL_append` in the default local.conf generated by envsetup.sh. But since I wanted to do it on a per-machine basis for now, it requires a bit more …
=> Remove connman

recipes-sota/fit-conf/fit-conf.bb
fit-conf should be a machine specific package instead of being a arch
specific package.
=> fit-conf: se PACKAGE_ARCH to ${MACHINE_ARCH}

recipes-sota/aktualizr/aktualizr_git.bb
Some shell require the -e argument when using escape sequences
in echo. This has been observed when building images on a
Fedora machine, where the configuration files ended up including
"\n" sequences instead of newlines.
=> aktualizr: use echo -e when using escape sequences

scripts/lib/wic/plugins/source/otaimage.py
do_image_wic task is a standalone task that depending on
do_image_ota_ext4, so it's possible that do_image_wic runs
(taskhash contaminated) but do_image_ota_ext4 does not (taskhash not
contaminated), in which case, the otaimage would be in DEPLOY_DIR_IMAGE
instead of in IMGDEPLOYDIR, so we need check both of them.
Also, the logger.error is not supposed to raise a error, it just
prints out a error message, so we should use WicError.
And another typo is it checks IMGDEPLOYDIR but reports DEPLOY_DIR_IMAGE
not exist, also fix that.
=> wic:plugins:otaimage.py: fix a potential issue

README.adoc, lib/oeqa/selftest/cases/updater.py, recipes-devtools/valgrind/files/bug344802-unhandled-0xec510f1e.patch, recipes-devtools/valgrind/valgrind_%.bbappend, recipes-sota/aktualizr/aktualizr_git.bb, recipes-sota/aktualizr/files/run-ptest
The needed CMake trickery is actually quite small!
But it copies the whole build and source directories on the device, which causes some rather long build times.
Tests are run under valgrind, with regular release compilation flags.
To run:
- ~~use these changes: https://github.com/advancedtelematic/aktualizr/pull/1119~~
- add `aktualizr-ptest` and `ptest-runner` in `IMAGE_INSTALL_append`
- (edit) also add `PTEST_ENABLED_pn-aktualizr = "1"` to the bitbake configuration
- build an image
- run `ptest-runner` on the device
On my last run under qemu, the only error was:
```
[ RUN      ] fetcher.test_pause_ostree
created: /tmp/aktualizr-7819-b833-8d28-c0e1/dd1f-9831-dir
Bootstraping DB to version 18
...
Fetcher: nothing to pause
Fetcher: nothing to resume
Fetcher: already paused
client_pkey not …
```
=> ptest for aktualizr

classes/image_types_ostree.bbclass, classes/sota.bbclass, conf/layer.conf
Remove "https://example.com/" as a default value of GARAGE_TARGET_URL.
Bitbaked against https://github.com/advancedtelematic/aktualizr/tree/feat/OTA-2418/remove-example.com branch and tested 'happy path' (device registration and new updates installation) for two cases 
1. default value of GARAGE_TARGET_URL, which is ""
2. GARAGE_TARGET_URL set to "https://example.com/" in local.conf
=> OTA-2418: Remove example.com URL from automated garage-sign usage

lib/oeqa/selftest/cases/testutils.py, lib/oeqa/selftest/cases/updater_qemux86_64_ptest.py, recipes-sota/aktualizr/aktualizr_git.bb, recipes-sota/aktualizr/files/run-ptest
Still has some failures at the moment, also the full output is often cropped for some unknown reason (the summary of which tests are passing and which aren't still appears in full)
=> Add oe-selftest for aktualizr ptest run on qemu

README.adoc, lib/oeqa/selftest/cases/updater_qemux86_64_ptest.py
If ctest is interrupted (e.g. timeout), its partial output will be in /tmp/aktualizr-ptest.log.tmp
=> More robust aktualizr-ptest printing of errors

lib/oeqa/selftest/cases/updater_qemux86_64_ptest.py, recipes-sota/aktualizr/aktualizr_git.bb
Some of our tests use pathlib which ends up in there...
Seems to be a problem on sumo at least, don't know how we haven't noticed on master... Still running tests to confirm!
=> Make aktualizr-ptest depend on python3-misc

README.adoc, recipes-sota/config/aktualizr-polling-interval.bb, recipes-sota/config/files/60-polling-interval.toml
Can be used for testing purposes after we increase the default polling interval in aktualizr. We no longer recommend anything less than an hour for production use cases, but it's still convenient to poll more frequently while testing.
FYI @alexhumphreys and @koshelev. This should probably get merged and backported (and the quickstart guide updated) before we merge https://github.com/advancedtelematic/aktualizr/pull/1212.
=> aktualizr-polling-interval: new config fragment.

classes/sota.bbclass
Move sota to DISTROOVERRIDES from OVERRIDES, it should be a distro
overrides.
This change also let 'sota' to be in front of 'forcevariable' in
OVERRIDES, since 'forcevariable' should always be the last overrides.
=> sota.bbclass: move sota to DISTROOVERRIDES

recipes-sota/aktualizr/aktualizr_git.bb
Not urgent, just seemed like it was time to do it before we do the next round of backporting.
=> aktualizr: bump garage sign to version 0.7.0-3-gf5ba640.

scripts/ci/oe-selftest.sh
So it's a PR on master because it's a change in the bitbake docker image.
=> Work around oe-selftest bug on sumo/thud

scripts/ci/checkout-oe.sh
It didn't work if the manifest already had a revision specified
=> Fix PIN_LIST in checkout-oe.sh

scripts/ci/checkout-oe.sh
Was causing problem with cache when updater-repo was updated
Another weird bash pull request, sorry.
=> Fix pre-clean of repo manifests

classes/image_types_ostree.bbclass
This aligns the OSTree rootfs output to be closer to what is documented in the OSTree documentation and the Filesystem Hierarchy Standard:
https://ostree.readthedocs.io/en/latest/manual/adapting-existing/
=> Follow Filesystem Hierarchy Standard

lib/oeqa/selftest/cases/updater_qemux86_64.py, scripts/ci/configure.sh, scripts/ci/gitlab/docker.yml, scripts/ci/gitlab/tests.yml
So that `before_script` can be used for additional steps when sub-classing.
Will be useful for making https://github.com/advancedtelematic/aktualizr/pull/1262 work with tags.
=> Move `before_script` gitlab steps to `script`

recipes-core/images/initramfs-ostree-image.bb
It is common for machine configurations to set EXTRA_IMAGEDEPENDS, which
can end up causing circular dependencies when building the initramfs
image (they are usually only required for the actual rootfs image).
=> initramfs-ostree-image: unset EXTRA_IMAGEDEPENDS to avoid extra dependencies

conf/local.conf.sample.append
Missed that somehow when we did the renaming.
=> local.conf.sample: fix provisioning naming.

classes/sota_freedom-u540.bbclass
meta-riscv now generates a fitImage by default for the freedom-u540
machine so remove the unneeded overrides.
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>
=> freedom-u540: Remove the fitImage overrides

recipes-connectivity/connman/connman_%.bbappend, recipes-connectivity/connman/files/0001-tmpfiles-script-do-not-create-the-resolv.conf-symlin.patch, recipes-connectivity/networkd-dhcp-conf/files/clean-connman-symlink.service, recipes-connectivity/networkd-dhcp-conf/files/resolvconf-clean, recipes-connectivity/networkd-dhcp-conf/networkd-dhcp-conf.bb
Fix for OTA-3401.
In summary, moving from using connman to systemd-networkd broke dns.
This fix allows:
- move from current version with connman to new versions with systemd-networkd (even without hack). This could maybe be upstreamed in some form
- move from old versions with connman to this one, with a systemd hack at boot (fix the broken symlink)
=> Connman 2 systemd fix

recipes-connectivity/connman/connman_%.bbappend, recipes-connectivity/connman/files/0001-tmpfiles-script-do-not-create-the-resolv.conf-symlin.patch, recipes-connectivity/networkd-dhcp-conf/files/clean-connman-symlink.service, recipes-connectivity/networkd-dhcp-conf/files/resolvconf-clean, recipes-connectivity/networkd-dhcp-conf/networkd-dhcp-conf.bb, recipes-sota/aktualizr/aktualizr_git.bb, scripts/qemucommand.py
Fix for OTA-3401.
In summary, moving from using connman to systemd-networkd broke dns.
This fix allows:
- move from current version with connman to new versions with systemd-networkd (even without hack). This could maybe be upstreamed in some form
- move from old versions with connman to this one, with a systemd hack at boot (fix the broken symlink)
=> Connman fix master

scripts/qemucommand.py
By default, qemu monitor gets attached to stdio, and that interferes with the test output.
We also don't need vga options in nographic mode.
Signed-off-by: Eugene Smirnov <evgenii.smirnov@here.com>
=> qemucommand.py: redirect qemu monitor to null chardev

recipes-sota/aktualizr/aktualizr_git.bb
Oddly, this started happening:
ERROR: aktualizr-1.0+gitAUTOINC+03778511cc-7 do_package_qa: QA Issue:
/usr/lib/aktualizr/ptest/src/tests/sota_tools/headers_response_server.py
contained in package aktualizr-ptest requires /usr/bin/python3, but no
providers found in RDEPENDS_aktualizr-ptest? [file-rdeps]
However, the python3 binary is already provided by python3-modules but
for some reason the qa check tool trips on it. We need to add an
explicit `python3-core` in the list.
=> Fix error during package_qa with aktualizr-ptest

lib/oeqa/selftest/cases/updater_qemux86_64.py
Use --wait-until-provisioned option while getting aktualizr status in the ip secondary tests
=> Use --wait-until-provisioned option for IP Secondary Test

conf/layer.conf
Zeus is the next OE release, scheduled to be released in October/2019.
=> layer.conf: add zeus to compatible release series

recipes-sota/aktualizr/aktualizr_git.bb
Why were `aktualizr-repo` and `aktualizr-cert-provider` listed in `RDEPENDS_${PN}-host-tools`? I see them added in 7ec1ffc4 but I'm wondering if that was really desirable or necessary. After renaming `aktualizr-repo`, I got a complaint for `uptane-generator`, so I removed it to solve the problem, as it wasn't doing anything. Not sure why the reference to `aktualizr-cert-provider` is necessary either, but I left it untouched. @liuming50 do you have any insight here?
=> aktualizr: aktualizr-repo was renamed to uptane-generator.

README.adoc
In the wake of https://github.com/advancedtelematic/aktualizr/pull/1410. That PR must get merged before this can be.
Also: should the links point to the docs portal instead of aktualizr's github pages?
=> README: update and restructure the links to the dev portal.

classes/image_types_ostree.bbclass
This fixes an unforeseen issue caused by https://github.com/advancedtelematic/meta-updater/pull/489.
When `ostree commit` is used it creates a ref with the passed in `OSTREE_BRANCHNAME`. The resulting ref file in ostree_repo contains the commit hash pertaining to this ref. This hash can then be used to locate the respective hash.commit file in ostree_repo which contains the metadata for that commit. One such piece of metadata is the ref-binding which is a list of ref names that correspond to this commit. 
The `ostree refs --create` added in the above pull request introduced an issue however. Using `ostree refs --create` creates a ref file in ostree_repo with the same hash as a preexisting commit. But this doesn't seem to modify the commit metadata at all.
This leads to problems when …
=> image_types_ostree: Fix OSTree ref-bindings

recipes-sota/aktualizr/aktualizr_git.bb
The systemd functionality in aktualizr is not currently used for anything, so there's no reason to use it.
=> aktualizr: remove systemd from PACKAGECONFIG.

recipes-connectivity/networkd-dhcp-conf/networkd-dhcp-conf.bb
We were setting PACKAGE_ARCH to MACHINE_ARCH anyway, so this wasn't helping anything.
Addresses the last comment from @shr-project in https://github.com/advancedtelematic/meta-updater/issues/603#issuecomment-546544016.
=> networkd-dhcp-conf: Remove allarch.

recipes-sota/aktualizr/aktualizr_git.bb
The compile step was removed by mistake in ec1ac0617b120813d6450dffe1aa8d4868e37332!
=> Fix aktualizr-ptest breakage

lib/oeqa/selftest/cases/updater_raspberrypi.py
See https://github.com/advancedtelematic/meta-updater-qemux86-64/pull/37
=> Remove a now unnecessary hack in rpi oe-selftests

classes/image_types_ostree.bbclass, classes/image_types_ota.bbclass
No functional changes, rename OTA_IMAGE_ROOTFS to TAR_IMAGE_ROOTFS
since the later is a more common name.
=> meta: change OTA_IMAGE_ROOTFS to TAR_IMAGE_ROOTFS

classes/sota_raspberrypi.bbclass, recipes-sota/aktualizr/aktualizr_git.bb
The broadcom firmware now needs device trees to be present in/boot to
set it up.
=> Fix uart output on recent raspberrypi3

.gitlab-ci.yml
Also publish images as artifact so that they can directly be downloaded for tests.
Having this job, would have been useful to test #629 without bitbaking anything manually.
I'm not enabling oe-selftests everywhere because it currently does not test much more effectively than an image build run. (subject to debate)
=> Build core-image-minimal for rpi on CI

classes/image_types_ostree.bbclass
Change to inherit features_check, since distro_features_check has been
deprecated in OE.
=> image_types_ostree.bbclass: do not inherit distro_features_check

recipes-sota/aktualizr/aktualizr_git.bb
Still haven't sorted out why `aktualizr_test` is failing, though.
=> aktualizr: Bump to latest for ptest fixes for C API tests.

conf/distro/sota.conf.inc
In 25a17f0346ab05b3212bb280e4a8b622bcf99bce, poky sets
reproducible_build by defaults. However, it is quite complex as it tries
to compute a plausible timestamp from source files, in a reproducible
ways.
Setting the timestamps to 0, just like ostree, is probably safer in our
case, so let's switch to our old behavior.
Tagging @agners who originally proposed this enhancement.
=> Force a simple reproducible build mechanism

lib/oeqa/selftest/cases/testutils.py, scripts/qemucommand.py, scripts/run-qemu-ota
This is intended to help with keeping around older versions of images with a similarly old bootloader.
@Raigi I'm hoping this is what you *actually* need for keeping around old images. Using this should give you the same features as https://github.com/advancedtelematic/meta-updater/pull/599 but without having to mess with clearing credentials. To use this, you'll need to copy the ota-ext4 image and the u-boot rom in your deploy directory and then launch qemu with something like `../meta-updater/scripts/run-qemu-ota --no-gui --machine qemux86-64 --uboot ./u-boot-qemux86-64.rom ./core-image-minimal-qemux86-64.ota-ext4`. What do you think?
=> Add --uboot flag to specify path to a custom u-boot rom.

recipes-sota/aktualizr/aktualizr-device-prov-hsm.bb, recipes-sota/aktualizr/aktualizr_git.bb
Depends on https://github.com/advancedtelematic/aktualizr/pull/1471.
=> Set PKCS11_ENGINE_PATH when using aktualizr with HSM

.gitlab-ci.yml
Nightly schedules are interfering with oft pipeline nightly schedules, so I would like to disable meta-updater pipelines from triggering otf on schedules.
=> Don't trigger otf on nightly meta-updater schedules

classes/image_repo_manifest.bbclass, classes/sota.bbclass
repo is requiring python to be able to work correctly, add python to
HOSTTOOLS_NONFATAL as well, meanwhile, combine HOSTTOOLS_NONFATAL
definitions in sota.bbclass.
image_repo_manifest is actually a image bbclass, move it to
IMAGE_CLASSES instead of inheriting it in sota.bbclass.
=> meta: add python to HOSTTOOLS_NONFATAL

recipes-connectivity/zabbix/zabbix_%.bbappend
Signed-off-by: Kostiantyn Bushko <kbushko@intellias.com>
Zabbix configuration recipe allows to configure zabbix_agernt in order to connect to zabbix_server app:
Options:
SOTA_COMM_CONF_ZABBIX_SERVER // set the zabbix "Server" address
SOTA_COMM_CONF_ZABBIX_SERVERACTIVE // zabbix "ServerActive" address
SOTA_COMM_CONF_ZABBIX_HOSTNAME // zabbix "Hostname"
=> Add Zabbix configuration recipe

conf/local.conf.nonostree.append, scripts/envsetup.sh, scripts/qemucommand.py, scripts/run-qemu-ota
Signed-off-by: Kostiantyn Bushko <kbushko@intellias.com>
This is draft PR for non OSTree image build, currently only for qemyx86-64.
1. Setup environment:
$ source envsetup.sh qemux86-64 "path-to-yocto-build-folder" poky
2. Build:
$bitbake core-image-minimal
3. Run QEMU:
$ ./run-qemu-ota --uboot-enable=no
=> build and run image without ostree support for qemux86-64

recipes-sota/aktualizr/files/aktualizr.service
aktualizr.service needs run after nss-lookup.target to ensure DNS
resolving is ready.
=> aktualizr: relies on nss-lookup.target

recipes-sota/aktualizr/aktualizr_git.bb
hmi-stub was replaced by libaktualizr-demo-app and is no longer part of this recipe. That leaves the aktualizr-examples package empty, so just get rid of it.
=> aktualizr: Remove unused hmi-stub and examples package.

recipes-test/demo-network-config/secondary-network-config.bb
- Allow Secondary to get a dynamic IP address from a router's DHCP server so it has an access to Internet. Statically defined IP address is still there and dedicated solely for communication with Primary.
- bump the latest aktualizr version that fixes the target name (filepath) reported to BE in a device manifest.
=> Enable internet access on Secondary

classes/image_types_ostree.bbclass
OSTree uses the "version" metadata field in various places, e.g. in
ostree admin status. Use DISTRO_VERSION as default version number
source. This gives a more human readable version number to a
particular OSTree:
$ ostree admin status
* torizon f1825d8a8f89c48cc0915ea059bd23463a97655757a53ae0ab0fe7a97e1ebeb2.0
Version: 3.0+snapshot-20200128
origin refspec: f1825d8a8f89c48cc0915ea059bd23463a97655757a53ae0ab0fe7a97e1ebeb
=> image_types_ostree: set version metadata field

recipes-connectivity/connman/connman_%.bbappend, recipes-connectivity/connman/connman_1.35.bbappend
Also still set RPROVIDES for all other versions.
Fixes the AGL build if we want to bump the pinned versions of meta-updater to the latest.
=> connman: Only apply our patch to 1.35.

classes/sota_m3ulcb.bbclass
The file name of sota has been changed in AGL, so change it to apply.
Signed-off-by: Minori Yasumura <minori@witz-inc.co.jp>
=> Rename defconfig and bootfiles

.gitignore, lib/oeqa/selftest/cases/testutils.py, lib/oeqa/selftest/cases/updater_qemux86_64.py
Porting oe-selftest cases for non-ostree image
=> Feat/ota 4310/non ostree/oe tests

recipes-sota/aktualizr/aktualizr_git.bb
Aktualizr and garage-sign are also bumped in the process.
=> Update aktualizr recipe to use new .so names

classes/image_types_ostree.bbclass
Most of the README content has been moved to the docs portal, so provide the direct link.
=> image_types_ostree: update doc link.

recipes-sota/aktualizr/aktualizr_git.bb
Depends on https://github.com/advancedtelematic/aktualizr/pull/1619.
=> aktualizr: Get garage-sign from the new AWS bucket.

recipes-sota/aktualizr/aktualizr_git.bb
Also bump the garage-sign version. New version includes fixes for supporting targets > 2 GB.
=> aktualizr: Bump to 2020.5 and get garage-sign from the new AWS bucket.

recipes-sota/aktualizr/aktualizr_git.bb
This fixes a following QA warning:
| WARNING: aktualizr do_package_qa: QA Issue: aktualizr rdepends on
| u-boot-fw-utils, but it isn't a build dependency, missing
| u-boot-fw-utils in DEPENDS or PACKAGECONFIG? [build-deps]
=> aktualizr: fix a dependency QA warning

classes/image_types_ostree.bbclass, classes/image_types_ota.bbclass
Hi, this are smaller improvements to the OSTree image tasks. Most notably it changes how /home folder is stored to align with what Fedora CoreOS is doing and what upstream OSTree today uses as the modern approach.
=> OSTree task improvements

classes/image_types_ostree.bbclass, classes/sota_sanity.bbclass, recipes-sota/aktualizr/aktualizr-shared-prov.bb, recipes-sota/aktualizr/aktualizr_git.bb
The current sanity check are too strict for some boolean variables,
introduce sota_check_boolean_variable to allow a boolean value to be
set like yes/y/true/t/1 or no/n/false/f/0.
=> sota_sanity.bbclass: introduce sota_check_boolean_variable

recipes-core/images/initramfs-ostree-image.bb
To avoid generating a qemuboot.conf for qemu machines, it's useless for
a initramfs image.
=> initramfs-ostree-image: drop qemuboot from IMAGE_CLASSES

classes/image_types_ostree.bbclass, classes/image_types_ota.bbclass
This merge request uses the OSTree commit checksum as source reference in the OSTree deployment task `do_image_ota`. This guarantees that the exact commit this build commited in `do_image_ostreecommit` actually gets deployed.
It also makes sure that `origin refspec` appears in `ostree admin status`, and hence will be used when using `ostree admin upgrade`. This is similar to what #687 tries to achieve.
=> Use checksum as deployment source and refspec in the deployment

recipes-extended/collectd/collectd_%.bbappend, recipes-sota/aktualizr/aktualizr-collectd.bb, recipes-sota/aktualizr/files/aktualizr-collectd.conf
Collectd has already a lot of monitoring features we want out of the box.
Simple usage is to build with `IMAGE_INSTALL_append = " aktualizr-collectd"`, then stats can be retrieved with 
```
scp  root@localhost:'/var/lib/collectd/*/processes-aktualizr/ps_rss.rrd' .
```
And a simple graph of the last 10 minutes:
```
rrdtool graph /tmp/graph.png -a PNG --start end-10m --title="Aktualizr Memory" 'DEF:mem=ps_rss.rrd:value:AVERAGE' 'LINE1:mem#ff0000:Memory'
```
=> Adding collectd configuration for aktualizr

classes/image_types_ostree.bbclass
The OSTree commit command allows to add metadata to the commit. This
might be customized in a distro layer for distribution specific needs.
Allow to pass extra arguments using EXTRA_OSTREE_COMMIT variable
(using a variable named similar to EXTRA_OEMAKE used to pass extra make
arguments).
=> image_types_ostree: allow to add layer specific OSTree commit arguments

classes/image_types_ostree.bbclass
When setting `OSTREE_DEPLOY_DEVICETREE` to 1, it will by default deploy
all the device tree blobs present in `KERNEL_DEVICETREE`. Adding
`OSTREE_DEVICETREE` would allow specifying a specific device tree blob
(or several dtbs), thus resulting in only the specified ones in the
image. This is particularely useful because ostree selects the first
device tree it finds in /boot, and discards the remaining ones.
=> image_types_ostree: allow specifying a device tree to deploy

recipes-sota/aktualizr/files/aktualizr.service
From the systemd.special(7) man page section boot-complete.target:
This target is intended as generic synchronization point for services
that shall determine or act on whether the boot process completed
successfully.
Let's make use of the target. Since aktualizr by default marks a boot
as successful, we consider aktualizr.service a service which needs to
be executed on successful boot (hence after the boot-complete.target).
This allows to declare a service as crucial by simply ordering it before
the boot-complete.target. The systemd example service
systemd-boot-check-no-failures.service can serve as an example.
This change does not add any service dependency by default as
boot-complete.target by default does not has any extra dependencies.
Note that rebooting in the failure case is not …
=> aktualizr: make use of boot-complete.target

classes/sota_m3ulcb.bbclass, classes/sota_minnowboard.bbclass, classes/sota_porter.bbclass, classes/sota_qemux86-64.bbclass, classes/sota_raspberrypi.bbclass, conf/distro/poky-sota-systemd.conf, conf/local.conf.nonostree.append, lib/oeqa/selftest/cases/updater_qemux86_64.py, recipes-connectivity/connman/connman_%.bbappend, recipes-connectivity/networkd-dhcp-conf/networkd-dhcp-conf.bb, recipes-test/images/primary-image.bb, recipes-test/images/secondary-image.bb
The name 'virtual' is a recipe specific concept but not a package
specific one, it's confusing that a package provides 'virtual/' names.
Let's drop 'virtual/' from network-configuration, to keep consistent
with yocto naming styles.
=> meta: change virtual/network-configuration to network-configuration

classes/sota.bbclass, lib/oeqa/selftest/cases/updater_qemux86_64.py, recipes-sota/aktualizr/aktualizr_git.bb
We did the work a while ago to make aktualizr-info work for Secondaries,
but until now we weren't putting the tool into the secondary-image we
use for testing. Now it's there. Actually, it's in every image that
inherits from sota.bbclass, which is probably a good thing.
=> Put aktualizr-info in a separate package and use it in Secondaries.

recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_0.0.1.bb
Hi,
Following the discussion on https://github.com/advancedtelematic/meta-updater/pull/728, I was taking a look at whether my modification had been backported or not. Seeing that the kernel/ramfs/dtb deployment had changed quite a bit, I took some time to see what changed and noticed that the device tree shipment reverted back to KERNEL_DEVICETREE. This PR just fixes that, since it would be pain to miss the next round of backporting :smile:
-antznin
=> ostree-kernel-initramfs: deploy dtbs from OSTREE_DEVICETREE

recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_0.0.1.bb
* otherwise it fails with useless error:
ostree-kernel-initramfs/0.0.1-r0/temp/run.do_install.3011' failed with exit code 1:
cp: -r not specified; omitting directory 'tmp-glibc/deploy/images/qemux86/'
WARNING: exit code 1 from a shell command.
because of
cp ${DEPLOY_DIR_IMAGE}/${OSTREE_KERNEL} $kerneldir/vmlinuz
in do_install will try to copy whole ${DEPLOY_DIR_IMAGE}/ when
${OSTREE_KERNEL} is empty
as reported in:
https://github.com/advancedtelematic/meta-updater/pull/740#issuecomment-651952735
=> ostree-kernel-initramfs: skip recipe when OSTREE_KERNEL is not defined

classes/image_types_ota.bbclass
When setting intertask dependencies, we should use PN instead of
IMAGE_BASENAME to refer to a image recipe, since PN is generated from
recipe file name, while IMAGE_BASENAME is a variable that could be
changed, it's not guaranteed to always equal to PN.
=> image_types_ota.bbclass: change IMAGE_BASENAME to PN

recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_0.0.1.bb
Following the changes in ostree's deployment of the kernel, initramfs
and devicetree in /lib/modules/$kver, the deployment method of the
device tree also changed. Instead of picking the first device tree it
finds at a given location, ostree looks at a file named devicetree, next
to kernel and initramfs in /lib/modules/$kver.
This commit modifies ostree-kernel-initramfs to deploy the devicetree
from the sota-defined variable OSTREE_DEVICETREE. It will pick the
first one from the list of device trees that OSTREE_DEVICETREE defines,
and copy it to /lib/modules/$kver. Note that since OSTREE_DEVICETREE
equals to KERNEL_DEVICETREE when it isn't explicitly defined, it could
indeed be a list of device trees.
This defines the way ostree picks the devicetree …
=> ostree-kernel-initramfs: fix devicetree deployment

recipes-connectivity/nfs-utils/nfs-utils/nfs-home-mount.service, recipes-connectivity/nfs-utils/nfs-utils_%.bbappend
nfs-mountd.service and nfs-statd.service rely on /var/lib/nfs to be
present in rootfs, or else they would run into problems for some files
missing in it.
But a ostree/ota rootfs does not have that directory (removed during
do_image), to fix that, we now copy them to /var/local/lib/nfs and
mount it to /var/lib/nfs at runtime, which is done in
nfs-home-mount.service.
nfs-mountd.service and nfs-statd.service need run after
nfs-home-mount.service.
=> nfs-utils: fix nfs systemd daemons runtime issues

scripts/qemucommand.py
The functionality was (presumably unintentionally) removed, but the option was still present.
=> qemucommand: Restore custom booloader parameter.

recipes-connectivity/nfs-utils/nfs-utils_%.bbappend
* nfs-home-mount.service is installed by do_install_append_sota, so only when sota is enabled
but it was always added to SYSTEMD_SERVICE_ even when sota wasn't enabled resulting in
do_patch failure:
nfs-utils-2.5.1-r0 do_package: SYSTEMD_SERVICE_nfs-utils value nfs-home-mount.service does not exist
* use sota override everywhere
* fix issues introduced in
https://github.com/advancedtelematic/meta-updater/pull/753
=> nfs-utils: don't add nfs-home-mount.service without sota enabled

classes/image_repo_manifest.bbclass, conf/distro/sota.conf.inc, recipes-test/big-update/big-update_1.0.bb, recipes-test/big-update/big-update_2.0.bb
Fixes https://github.com/advancedtelematic/meta-updater/issues/684.
@shr-project Can you confirm that this addresses the python concern you've raised? Are there further changes we should make?
=> Inherit python3native instead of using HOSTTOOLS.

classes/sota_raspberrypi.bbclass
This was changed in a907c3261ef583f898803706cd596d372c6644cb of meta-raspberrypi. This also requires 0b5292d13692ba074dc85227233e3a819d944204 in meta-updater-raspberrypi (see https://github.com/advancedtelematic/meta-updater-raspberrypi/pull/87).
=> sota_raspberrypi: Use new variable for bootfiles path.

classes/image_repo_manifest.bbclass
Now we have changed to inherit python3native to provide python3 binary
for repo, then we need explicitly call python3 to execute repo, or else
it will firstly try to locate python which will fail if python is not
in HOSTTOOLS.
This fixes a following warning:
| Android repo tool failed to run; manifest not copied
=> image_repo_manifest.bbclass: explicitly call python3

recipes-sota/aktualizr/aktualizr_git.bb
This is just a quick cherry-pick to get ptest working correctly in aktualizr's CI.
=> aktualizr: Bump to latest and install headers in dev package.

classes/image_repo_manifest.bbclass
* failing "which repo" causes the run.buildinfo_manifest task to fail
before it even reaches the test for empty repotool variable:
dash -x some-image/1.0-r2/temp/run.buildinfo_manifest.80233
+ export systemd_system_unitdir=/usr/lib/systemd/system
+ export systemd_unitdir=/usr/lib/systemd
+ export systemd_user_unitdir=/usr/lib/systemd/user
+ buildinfo_manifest
+ which repo
+ repotool=
+ bb_sh_exit_handler
+ ret=1
+ [ 1 != 0 ]
+ echo WARNING: exit code 1 from a shell command.
WARNING: exit code 1 from a shell command.
+ exit 1
causing nasty long python exception from do_image task
with this fix, it just shows an warning again:
dash -x some-image/1.0-r2/temp/run.buildinfo_manifest.80233
+ export systemd_user_unitdir=/usr/lib/systemd/user
+ buildinfo_manifest
+ which repo
+ true
+ repotool=
+ …
=> image_repo_manifest.bbclass: fix build when there is no repo on host

recipes-connectivity/networkd-dhcp-conf/networkd-dhcp-conf.bb
* it's REQUIRED_DISTRO_FEATURES not REQUIRED_DISTRO_FEATURES_
* inherit features_check to actually respect REQUIRED_DISTRO_FEATURES
and fix:
ERROR: networkd-dhcp-conf-1.0-r1 do_package_qa: QA Issue: networkd-dhcp-conf: recipe doesn't inherit features_check [unhandled-features-check]
* fix:
commit 4ae9917bf2475c118e8015ec7a2ce10bd01a0124
Author: Mykhaylo Sul <ext-mykhaylo.sul@here.com>
Date:   Fri Nov 1 11:44:44 2019 +0100
OTA-3988: Don't build the networkd-dhcp recipe if systemd is not included into the disto feature list
=> networkd-dhcp-conf: fix REQUIRED_DISTRO_FEATURES

classes/sota.bbclass, recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_0.0.1.bb
Previous initramfs fit specific workaround was removed as part of commit
6eecf1593d, causing ostree to provide an init argument as part of the
kernel command line arguments when it is not really needed.
Bring back the workaround by simply generating an empty file in case
kernel image type is fit and initramfs is also used by the target.
=> ostree-kernel-initramfs: add back initramfs fit workaround

recipes-sota/aktualizr/aktualizr-device-prov-hsm.bb, recipes-sota/aktualizr/aktualizr-device-prov.bb, recipes-sota/aktualizr/aktualizr-shared-prov.bb, recipes-sota/aktualizr/aktualizr_git.bb
Because every aktualizr package was depending on aktualizr-configs, all
of the default configs were getting installed to /usr/lib/sota, despite
that by default none of them were ever used on the device. That
dependency has been removed.
The provisioning recipes still install the recipes they need to the
default location that aktualizr actually uses (/usr/lib/sota/conf.d). If
you want to use anything else, a specific recipe should be created to do
so.
This change rendered the aktualizr-host-tools package useless, so it has
been removed.
=> aktualizr: Don't put unused configs in the image.

lib/oeqa/selftest/cases/testutils.py
extend wait time for provisioning in tests. testutils.py verifyProvisioned check fails frequently when runs on CI. 
Signed-off-by: Anatoliy Odukha <aodukha@gmail.com>
=> test in quemu on CI may need more time to prepare env

scripts/ci/Dockerfile.checkout
The latest version of repo requires python3.6+, but the default Debian package is fine with the default python3 package (although it complains about experimental support).
=> Use python3 to get repo working again.

classes/image_types_ota.bbclass
It is port of  https://github.com/advancedtelematic/meta-updater/pull/787 for dunfel branch
CI for this https://main.gitlab.in.here.com/olp/edge/ota/connect/client/meta-updater/-/pipelines/1706123
Original description:
We dont have to maintain our own function calculate_size and use
dd/mkfs.ext4 to generate ota-ext4 image, they have been done in OE
by get_rootfs_size/oe_mkext234fs functions, we could just use them.
The major benefit could be we can sync the future fixes/changes in
these functions from OE, also avoid maintaining some duplicated code in
image_types_ota.bbclass.
=> calculate_size function is redundant

classes/image_types_ota.bbclass
We dont have to maintain our own function calculate_size and use
dd/mkfs.ext4 to generate ota-ext4 image, they have been done in OE
by get_rootfs_size/oe_mkext234fs functions, we could just use them.
The major benefit could be we can sync the future fixes/changes in
these functions from OE, also avoid maintaining some duplicated code in
image_types_ota.bbclass.
=> image_types_ota.bbclass: call oe_mkext234fs to make ota-ext4 image

classes/image_types_ota.bbclass
* it doesn't automatically pass "-t ext4", because here we're calling
mke2fs as mkfs.ota-ext4 instead of mkfs.ext4
so the resulting was now ext2 instead of ext4
$ file image-raspberrypi4.rootfs.ota-ext4
image-raspberrypi4.rootfs.ota-ext4: Linux rev 1.0 ext2 filesystem data, UUID=15862fcd-6204-486b-a4c6-fdf7b1710797, volume name "otaroot" (large files)
after this fix:
$ file image-raspberrypi4.rootfs.ota-ext4
image-raspberrypi4.rootfs.ota-ext4: Linux rev 1.0 ext4 filesystem data, UUID=3709e65c-1d2b-4280-85d1-638f5f9c3cc0, volume name "otaroot" (extents) (64bit) (large files) (huge files)
that's why metadata_csum and other features enabled by default
in ext4 were now missing after
https://github.com/advancedtelematic/meta-updater/pull/787
we can drop 64bit feature as well, it's also enabled …
=> image_types_ota.bbclass: pass -t ext4 to mke2fs

classes/image_types_ostree.bbclass
In commit d13ec585ae677affd88b9d92c6ea135cc249b2fa:
[ image_types_ostree: use OSTree repo location for lockfiles ]
A lockfile ${OSTREE_REPO}/ostree.lock was added to prevent concurrent
access to the repository by multiple bitbake instances, but it should
not only apply to ostreecommit task, but ota task also needs it.
This fixes a following race condition error:
| | ERROR: Execution of '.../temp/run.do_image_ostreecommit.34262' failed with exit code 1:
| error: Writing content object: Creating temp file: No such file or directory
=> image_types_ota.bbclass: get lock before accessing OSTREE_REPO

classes/image_types_ota.bbclass
Avoid removing 64bit and metadata_csum by default and prefer the
standard ext4 features instead.
64bit enables the file system to be larger than 2^32 blocks and
metadata_csum enables metadata checksumming, both of which are
enabled by default on recent mke2fs releases.
It is unclear why 64bit was disabled by looking at the git history, but
my assumption would be that either kernel or userspace was old enough
for this feature to not be supported/available. Since this option is
currently used by most distros by default, it should now be safe to
enable it (requires kernel >= 2.6.28).
metadata_csum was disabled in 4d34fa53db to make the u-boot tooling work
with the ext4 file system (when saving environment), but the correct fix
should instead be a fix at the userspace tooling instead, since …
=> image_types_ota.bbclass: use standard ext4 features

recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_0.0.1.bb
It's a metadata-only recipe and all contributors have agreed that MIT would be preferable.
FYI @shr-project. This effectively replaces https://github.com/advancedtelematic/meta-updater/pull/801.
=> ostree-kernel-initramfs: Use MIT license.

recipes-test/big-update/big-update_2.0.bb
We had this PNBLACKLISTed for long time in webOS OSE builds, but fixing it is quite easy.
=> Fix big-update recipe

recipes-sota/fit-conf/fit-conf.bb, recipes-sota/ostree-initrd/ostree-initrd.bb, recipes-support/slcand-start/slcand-start.bb, recipes-test/big-update/big-update_2.0.bb
Backport https://github.com/advancedtelematic/meta-updater/pull/806 and https://github.com/advancedtelematic/meta-updater/pull/805 to dunfell branch as well.
=> Backport few fixes from master branch

recipes-sota/aktualizr/aktualizr_git.bb
* fails with latest oe-core/master with:
https://git.openembedded.org/openembedded-core/commit/meta/classes/cmake.bbclass?id=0fb6280432a36985590d9a714a5f11164aaebb51
because this prepend does "cd ${S}" and doesn't go back to ${B} and
cmake_do_configure function doesn't cd to ${B} anymore, resulting in:
| CMake Error at CMakeLists.txt:42 (message):
|   Aktualizr does not support building in the source tree.  Please remove
|   CMakeCache.txt and the CMakeFiles/ directory, then create a subdirectory to
|   build in: mkdir build; cd build; cmake ..
* drop this whole do_configure_prepend as git-native works fine:
aktualizr-native/1.0+gitAUTOINC+1255aa24fe-7/git$ grep Setting ../temp/log.do_configure
-- Setting version to 2020.10-0-g1255aa24f
aktualizr/1.0+gitAUTOINC+1255aa24fe-7/temp$ grep …
=> aktualizr: drop unnecessary do_configure_prepend

classes/image_types_ostree.bbclass
The purpose of prepare_ostree_rootfs prefunc is to ensure
do_image_rootfs runs from a clean ${OSTREE_ROOTFS} and call
oe.path.copyhardlinktree from ${IMAGE_ROOTFS} to ${OSTREE_ROOTFS}.
We dont have to maintain a prefunc to achieve that, it could be easily
done in do_image_ostree itself.
But the major reason for this change is to avoid hard links from
${IMAGE_ROOTFS} to ${OSTREE_ROOTFS}, which might lead to a Pseudo
abortion in some cases, which was observed when IMA/EVM is enabled
in rootfs.
There was a commit aiming to fix the Pseudo abortion, commit db099053:
[ image_types_ostree.bbclass: add fakeroot varflag to prepare_ostree_rootfs ]
but it's incomplete per later tests, there is still the case some old
inodes being used in ${IMAGE_ROOTFS} when do_rootfs runs, which causes
'rm -rf …
=> image_types_ostree.bbclass: drop prepare_ostree_rootfs prefunc

scripts/ci/Dockerfile.bitbake
Our pipelines for older releases of Yocto ( warrior, thud, zeus ) started failing a long time ago. Looks like this version also needs python2. At least it is the fastest way to fix pipelines.
=> Return python2 to Docker image

classes/image_types_ota.bbclass
Add support for ostree to automatically identify and use syslinux as the
preferred bootloader scheme when set via OSTREE_BOOTLOADER.
Not forcing a build-time dependency at do_image_ota as multiple
bootloaders are able to identify the syslinux format.
=> image_types_ota.bbclass: add support for syslinux as OSTREE_BOOTLOADER
